spring:
  application:
    name: university-course-management
  
  mvc:
    static-path-pattern: /static/**
  
  web:
    resources:
      static-locations: classpath:/static/
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/erp_stuff}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 600000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    default-schema: public

server:
  port: ${SERVER_PORT:8080}
  undertow:
    threads:
      io: 2
      worker: 32
    buffer-size: 1024
    direct-buffers: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    '[com.university.backend]': ${LOG_LEVEL:DEBUG}
    '[org.springframework.security]': ${SECURITY_LOG_LEVEL:DEBUG}
    '[org.springframework.web]': DEBUG
    '[org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping]': DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  jwt:
    secret: ${JWT_SECRET:local-development-secret-key-change-in-production-this-needs-to-be-at-least-512-bits-long-for-HS512-algorithm-so-adding-more-characters-here}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
  cors:
    allowed-origins: http://localhost:3000

# API Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
