spring:
  application:
    name: university-course-management
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/erp_stuff}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 900000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    default-schema: public

server:
  port: ${SERVER_PORT:8080}
  undertow:
    threads:
      io: ${UNDERTOW_IO_THREADS:4}
      worker: ${UNDERTOW_WORKER_THREADS:64}
    buffer-size: ${UNDERTOW_BUFFER_SIZE:1024}
    direct-buffers: ${UNDERTOW_DIRECT_BUFFERS:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    '[com.university.backend]': ${LOG_LEVEL:INFO}
    '[org.springframework.security]': ${SECURITY_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  jwt:
    secret: ${JWT_SECRET:production-secret-key-change-this-in-production-environment-this-needs-to-be-at-least-512-bits-long-for-HS512-algorithm-security}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

# API Documentation
springdoc:
  api-docs:
    path: swagger-ui/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
