name: Build and push backend Docker image to GHCR

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]
  workflow_dispatch: {}

env:
  BACKEND_APP_NAME: university-erp-backend

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.BACKEND_APP_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.BACKEND_APP_NAME }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Output pushed image name
        run: |
          echo "Pushed: ghcr.io/${{ github.repository_owner }}/${{ env.BACKEND_APP_NAME }}:latest"
