name: Deploy to Azure

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: university-erp-backend
  FRONTEND_IMAGE_NAME: university-erp-frontend
  AZURE_RESOURCE_GROUP: rg-university-erp
  BACKEND_APP_NAME: university-erp-backend
  FRONTEND_APP_NAME: university-erp-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repository owner
        run: |
          echo "REPO_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Extract metadata for backend
        id: backend-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWER }}/${{ env.BACKEND_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-

      - name: Extract metadata for frontend
        id: frontend-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWER }}/${{ env.FRONTEND_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.backend-meta.outputs.tags }}
          labels: ${{ steps.backend-meta.outputs.labels }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.frontend-meta.outputs.tags }}
          labels: ${{ steps.frontend-meta.outputs.labels }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure resources if they don't exist
        run: |
          # Create resource group if it doesn't exist
          az group create --name ${{ env.AZURE_RESOURCE_GROUP }} --location eastus --output none || true
          
          # Create app service plan (F1 - Free tier)
          az appservice plan create \
            --name asp-university-erp \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --location eastus \
            --sku F1 \
            --is-linux \
            --output none || true

      - name: Create/Update backend web app
        run: |
          # Create web app for containers if it doesn't exist
          az webapp create \
            --name ${{ env.BACKEND_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --plan asp-university-erp \
            --deployment-container-image-name ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWER }}/${{ env.BACKEND_IMAGE_NAME }}:latest \
            --output none || true

          # Set application settings
          az webapp config appsettings set \
            --name ${{ env.BACKEND_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --settings \
              WEBSITES_PORT=8080 \
              SERVER_PORT=8080 \
              SPRING_PROFILES_ACTIVE=prod \
              JAVA_OPTS="-Xmx512m -Xms256m -Djava.security.egd=file:/dev/./urandom" \
              WEBSITES_CONTAINER_START_TIME_LIMIT=180

          # Configure container settings AFTER setting environment variables
          az webapp config container set \
            --name ${{ env.BACKEND_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --container-image-name ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWER }}/${{ env.BACKEND_IMAGE_NAME }}:latest \
            --container-registry-url https://${{ env.REGISTRY }} \
            --container-registry-user ${{ github.actor }} \
            --container-registry-password ${{ secrets.GITHUB_TOKEN }}

      - name: Create/Update frontend web app
        run: |
          # Create web app for containers if it doesn't exist
          az webapp create \
            --name ${{ env.FRONTEND_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --plan asp-university-erp \
            --deployment-container-image-name ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWER }}/${{ env.FRONTEND_IMAGE_NAME }}:latest \
            --output none || true

          # Set application settings
          az webapp config appsettings set \
            --name ${{ env.FRONTEND_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --settings \
              WEBSITES_PORT=3000 \
              NODE_ENV=production \
              NEXT_PUBLIC_API_URL=https://${{ env.BACKEND_APP_NAME }}.azurewebsites.net \
              NEXT_PUBLIC_APP_URL=https://${{ env.FRONTEND_APP_NAME }}.azurewebsites.net

          # Configure container settings AFTER setting environment variables
          az webapp config container set \
            --name ${{ env.FRONTEND_APP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --container-image-name ${{ env.REGISTRY }}/${{ env.REPO_OWNER_LOWER }}/${{ env.FRONTEND_IMAGE_NAME }}:latest \
            --container-registry-url https://${{ env.REGISTRY }} \
            --container-registry-user ${{ github.actor }} \
            --container-registry-password ${{ secrets.GITHUB_TOKEN }}

      - name: Restart web apps
        run: |
          az webapp restart --name ${{ env.BACKEND_APP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
          az webapp restart --name ${{ env.FRONTEND_APP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}

      - name: Show deployment URLs
        run: |
          echo "🚀 Deployment completed!"
          echo "Backend: https://${{ env.BACKEND_APP_NAME }}.azurewebsites.net"
          echo "Frontend: https://${{ env.FRONTEND_APP_NAME }}.azurewebsites.net"
          
      - name: Check backend health after deployment
        run: |
          echo "⏳ Waiting for backend to start..."
          sleep 60
          
          echo "🔍 Checking backend health endpoint..."
          MAX_RETRIES=5
          RETRY_COUNT=0
          
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            echo "Attempt $((RETRY_COUNT + 1)) of $MAX_RETRIES..."
            
            if curl -f -v --max-time 30 https://${{ env.BACKEND_APP_NAME }}.azurewebsites.net/actuator/health; then
              echo "✅ Backend health check passed!"
              break
            else
              echo "❌ Health check failed on attempt $((RETRY_COUNT + 1))"
              RETRY_COUNT=$((RETRY_COUNT + 1))
              
              if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                echo "⏳ Waiting 30 seconds before retry..."
                sleep 30
              fi
            fi
          done
          
          if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
            echo "🚨 All health check attempts failed!"
            echo "📋 Attempting to download application logs for debugging..."
            
            az webapp log download \
              --name ${{ env.BACKEND_APP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
              --log-file backend-logs.zip || echo "Could not download logs"
              
            if [ -f backend-logs.zip ]; then
              echo "📄 Extracting logs..."
              unzip -l backend-logs.zip || echo "Could not extract logs"
            fi
            
            echo "🔍 Checking container logs..."
            az webapp log tail \
              --name ${{ env.BACKEND_APP_NAME }} \
              --resource-group ${{ env.AZURE_RESOURCE_GROUP }} || echo "Could not tail logs"
              
            exit 1
          fi
